version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: meteobatch
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  meteo-batch:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/meteobatch
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G

  api-meteo:
    build:
      context: C:\dev\back-end\api-meteo\
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge