api:
  token: 365aa8341e7624d79b34690e4e1d055b7019d6705feb718456ceea44bbc8a4cb
  url: https://api.meteo-concept.com/api/forecast/nextHours?token=
spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password:
  h2:
    console:
      enabled: 'true'
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true
    banner:
      location: classpath:banner.txt
