server:
  port: 8082

api:
  token: 365aa8341e7624d79b34690e4e1d055b7019d6705feb718456ceea44bbc8a4cb
  url: https://api.meteo-concept.com/api/forecast/nextHours?token=
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: SpringBootHikariCP
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true
    banner:
      location: classpath:banner.txt
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/changelog-master.xml
    default-schema: public