api:
  token: 365aa8341e7624d79b34690e4e1d055b7019d6705feb718456ceea44bbc8a4cb
  url: https://api.meteo-concept.com/api/forecast/nextHours?token=
spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true
    banner:
      location: classpath:banner.txt
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/changelog-master.xml
    default-schema: public